---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari-data-v1
  namespace: hajimari
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi