apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-llink
  namespace: dev-llink
  labels:
    app: dev-llink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-llink
  template:
    metadata:
      labels:
        app: dev-llink
    spec:
      containers:
      - name: littlelink-server
        image: ghcr.io/techno-tim/littlelink-server:latest
        ports:
        - containerPort: 3000
        env:
        - name: META_TITLE
          value: 'Pierre Constantineau'
        - name: META_DESCRIPTION
          value: 'Links for Dr J. Pierre Constantineau'
        - name: META_AUTHOR
          value: 'Pierre Constantineau'
        - name: META_KEYWORDS
          value: 'HomeLab, Keyboards, Arduino, Software, Hardware, Engineering'   
        - name: NAME
          value: 'Pierre Constantineau PhD'  
---
apiVersion: v1
kind: Service
metadata:
  name: dev-llink
  namespace: dev-llink
spec:
  selector:
    app: dev-llink-service
  ports:
    - protocol: TCP
      port: 80
      targetport: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-llink
  namespace: dev-llink
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: "ll.dev.jpto.dev"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dev-llink-service
            port:
              number: 80
  tls:
  - hosts: 
    - ll.dev.jpto.dev
    secretName: dev-llink-jptodev-tls-production              