apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-llink
  namespace: dev-llink
  labels:
    app: dev-llink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-llink
  template:
    metadata:
      labels:
        app: dev-llink
    spec:
      containers:
      - name: littlelink-server
        image: ghcr.io/techno-tim/littlelink-server:latest
        env:
        - name: META_TITLE
          value: 'Pierre Constantineau'
        - name: AVATAR_URL
          value: 'https://avatars.githubusercontent.com/u/1149816?v=4'  
        - name: GITHUB
          value: 'https://github.com/jpconstantineau'
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dev-llink-service
  namespace: dev-llink
spec:
  selector:
    app: dev-llink
  ports:
    - protocol: TCP
      port: 3000
      targetport: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-llink-ingress
  namespace: dev-llink
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: "ll.dev.jpto.dev"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dev-llink-service
            port:
              number: 80
  tls:
  - hosts: 
    - ll.dev.jpto.dev
    secretName: dev-llink-jptodev-tls-production              