apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-llink
  namespace: dev-llink
  labels:
    app: dev-llink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-llink
  template:
    metadata:
      labels:
        app: dev-llink
    spec:
      containers:
      - name: littlelink-server
        image: ghcr.io/techno-tim/littlelink-server:latest
        env:
        - name: META_TITLE
          value: 'Pierre Constantineau'
        - name: META_DESCRIPTION
          value: 'Links for Dr J. Pierre Constantineau'
        - name: META_AUTHOR
          value: 'Pierre Constantineau'
        - name: META_KEYWORDS
          value: 'HomeLab, Keyboards, Arduino, Software, Hardware, Engineering'   
        - name: LANG
          value: 'en'
        - name: META_INDEX_STATUS
          value: 'noindex'  
        - name: THEME
          value: 'Dark'  
        - name: NAME
          value: 'Pierre Constantineau PhD'  
        - name: BIO
          value: 'Software | Arduino | Keyboard Hardware/Firmware | Content Creator on YouTube | Outdoor Enthusiast'  
        - name: AVATAR_URL
          value: 'https://avatars.githubusercontent.com/u/1149816?v=4'  
        - name: GITHUB
          value: 'https://github.com/jpconstantineau'
        - name: LINKED_IN
          value: 'https://www.linkedin.com/in/pierre-constantineau-ab81394/'  
        - name: YOUTUBE
          value: 'https://www.youtube.com/@BlueMicroWirelessKeyboards'
        - name: DOCKERHUB
          value: 'https://hub.docker.com/repositories/jpconstantineau'
        - name: FOOTER
          value: 'Pierre Constantineau © 2023'   
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dev-llink
  namespace: dev-llink
spec:
  selector:
    app: dev-llink
  ports:
    - protocol: TCP
      port: 80
      targetport: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-llink
  namespace: dev-llink
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: "ll.dev.jpto.dev"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dev-llink
            port:
              number: 80
  tls:
  - hosts: 
    - ll.dev.jpto.dev
    secretName: dev-llink-jptodev-tls-production              