apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authelia
  namespace: argocd
spec:
  destination:
    namespace: authelia
    server: https://kubernetes.default.svc
  project: production
  source:
    helm:
    version: "0.8.57"
    repoURL: https://charts.authelia.com
  syncPolicy:
    automated:
      selfHeal: true