apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeview-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://raw.githubusercontent.com/benc-uk/kubeview/master/charts
    chart: kubeview
    targetRevision: '*'
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeview
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true