apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-iow-nginx-auth
  namespace: prod-iow
  labels:
    app: prod-iow-nginx-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-iow-nginx-auth
  template:
    metadata:
      labels:
        app: prod-iow-nginx-auth
    spec:
      containers:
      - name: nginx
        image: nginx:1.23-alpine-slim
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-iow-nginx-auth-service
  namespace: prod-iow
spec:
  selector:
    app: prod-iow-nginx-auth
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-iow-ingress-auth
  namespace: prod-iow
  annotations:
    hajimari.io/enable: "True"
    hajimari.io/appName: "IOW Prod - auth"
    hajimari.io/icon: "mdi:cloud"
    hajimari.io/targetBlank: "True"
    hajimari.io/group: "Production"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
    #traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  rules:
  - host: "iow.jpto.dev"
    http:
      paths:
      - pathType: Prefix
        path: /auth/
        backend:
          service:
            name: prod-iow-nginx-auth-service
            port:
              number: 80        
  tls:
  - hosts: 
    - iow.jpto.dev
    secretName: iow-jpto-tls-production