apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-podinfo
  namespace: dev-podinfo
  labels:
    app: dev-podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-podinfo
  template:
    metadata:
      labels:
        app: dev-podinfo
    spec:
      containers:
      - name: podinfo
        image: stefanprodan/podinfo
        ports:
        - containerPort: 9898 
---
apiVersion: v1
kind: Service
metadata:
  name: dev-podinfo-service
  namespace: dev-podinfo
spec:
  selector:
    app: dev-podinfo
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9898 
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-podinfo-ingress
  namespace: dev-podinfo
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: "podinfo.dev.jpto.dev"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: dev-podinfo-service
            port:
              number: 80
  tls:
  - hosts: 
    - podinfo.dev.jpto.dev
    secretName: dev-podinfo-jptodev-tls-production              